# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
cpus_per_task: 8
gpus_per_node: null
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: gpu
qos: null
comment: null
constraint: null
exclude: null
gres: v100:1
cpus_per_gpu: null
gpus_per_task: 1
mem_per_gpu: 50G
mem_per_cpu: null
account: project_2006174
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
  # - module load pytorch/2.4
  # - export SUBMITIT_EXECUTOR=slurm
  # - export SLURM_SRUN_PATH=/usr/bin/srun